apiVersion: charts.helm.k8s.io/v1
kind: Xl
metadata:
  name: xl-release
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  global:
    registry: docker.io
    logtostdout: true
    storageClassName: {{.Values.turboStorageClass}}
    repository: turbonomic
    tag: 8.3.4
    externalArangoDBName: arango.turbo.svc.cluster.local
  vcenter:
    enabled: true
  instana:
    enabled: true
  azure:
    enabled: true
  kubeturbo:
    enabled: true
  gcp:
    enabled: true
  aws:
    enabled: true
  nginxingress:
    enabled: false
  openshiftingress:
    enabled: true
  actionscript:
    enabled: true
  udt:
    enabled: true
  actionstream-kafka:
    enabled: false
  appdynamics:
    enabled: true
  appinsights:
    enabled: true
  dynatrace:
    enabled: true
  hpe3par:
    enabled: true
  horizon:
    enabled: false
  hyperflex:
    enabled: false
  hyperv:
    enabled: true
  netapp:
    enabled: true
  prometheus:
    enabled: true
  prometurbo:
    enabled: true
  servicenow:
    enabled: false
  ucs:
    enabled: true
  vmax:
    enabled: true
  vmm:
    enabled: true
  wmi:
    enabled: true
  snmp:
    enabled: true
  mssql:
    enabled: true
  mysql:
    enabled: true
  oracle:
    enabled: true
  tomcat:
    enabled: true
  jvm:
    enabled: true
  newrelic:
    enabled: true
  websphere:
    enabled: true
  weblogic:
    enabled: true
