apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  namespace: istio-system
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "210"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  members:
    - robot-shop
    - kubetoy